
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.


[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.3.0"

[[constraint]]
  name = "github.com/markbates/refresh"
  version = "1.2.0"

[[constraint]]
  name = "github.com/rakyll/statik"
  version = "0.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"
